form:
    resource: "@FormBundle/Controller/"
    type:     annotation
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
